
disabled_rules:
- trailing_whitespace
opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 30
    error: 60
function_parameter_count:
    warning: 3
    error: 5
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 400
    error: 600
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 5
    error: 10
reporter: "xcode"
